"""
Data Quality Service
--------------------

Evaluates the quality of datasets generated by the
Synthetic Data Intelligence Engine.

Author : Meera Sastry
Project: ClinicalTrialAI
"""

from __future__ import annotations

from datetime import datetime
from typing import List

import pandas as pd

from src.ic07.models.data_quality_issue import DataQualityIssue
from src.ic07.models.data_quality_metric import DataQualityMetric
from src.ic07.repositories.data_quality_repository import (
    DataQualityRepository,
)
from src.ic07.services.quality_rule_engine import QualityRuleEngine


class DataQualityService:
    """
    Service responsible for evaluating the quality of
    synthetic datasets.
    """

    def __init__(
        self,
        repository: DataQualityRepository,
    ) -> None:

        self.repository = repository

    # -------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------

    def evaluate(
        self,
        dataset_name: str,
        dataframe: pd.DataFrame,
    ) -> DataQualityMetric:
        """
        Evaluate the quality of a dataframe.

        Parameters
        ----------
        dataset_name
            Logical name of the dataset.

        dataframe
            Dataset to evaluate.

        Returns
        -------
        DataQualityMetric
        """

        metric = DataQualityMetric(
            dataset_name=dataset_name,
            total_records=len(dataframe),
        )

        issues: List[DataQualityIssue] = []

        metric.completeness_score = self._evaluate_completeness(
            dataset_name,
            dataframe,
            issues,
        )

        metric.uniqueness_score = self._evaluate_uniqueness(
            dataset_name,
            dataframe,
            issues,
        )

        #
        # Placeholder scores.
        # These will become more intelligent
        # in future milestones.
        #

        metric.validity_score = 100.0
        metric.consistency_score = 100.0
        metric.accuracy_score = 100.0
        metric.timeliness_score = 100.0

        metric.overall_score = self._calculate_overall_score(
            metric
        )

        metric.failed_records = len(
            {
                issue.row_number
                for issue in issues
            }
        )

        metric.status = self._determine_status(
            metric.overall_score
        )

        metric.evaluated_at = datetime.now()

        self.repository.save_metric(metric)

        for issue in issues:
            self.repository.save_issue(issue)

        return metric

    # -------------------------------------------------------------
    # Completeness
    # -------------------------------------------------------------

    def _evaluate_completeness(
        self,
        dataset_name: str,
        dataframe: pd.DataFrame,
        issues: List[DataQualityIssue],
    ) -> float:
        """
        Evaluate completeness by checking
        for missing values.
        """

        total_values = 0
        missing_values = 0

        for row_index, (_, row) in enumerate(
            dataframe.iterrows()
        ):

            for column, value in row.items():

                total_values += 1

                if QualityRuleEngine.is_missing(value):

                    missing_values += 1

                    issues.append(
                        DataQualityIssue(
                            dataset_name=dataset_name,
                            row_number=row_index + 1,
                            column_name=column,
                            issue_type="Missing Value",
                            severity="High",
                            expected_value="Non-empty",
                            actual_value=str(value),
                            suggestion="Populate a valid value",
                        )
                    )

        if total_values == 0:
            return 100.0

        return round(
            (
                (total_values - missing_values)
                / total_values
            )
            * 100,
            2,
        )


    # -------------------------------------------------------------
    # Uniqueness
    # -------------------------------------------------------------

    def _evaluate_uniqueness(
        self,
        dataset_name: str,
        dataframe: pd.DataFrame,
        issues: List[DataQualityIssue],
    ) -> float:
        """
        Evaluate uniqueness by identifying duplicate rows.
        """

        duplicate_rows = dataframe.duplicated(keep="first")

        duplicate_count = int(duplicate_rows.sum())

        for row_index in dataframe.index[duplicate_rows]:

            issues.append(
                DataQualityIssue(
                    dataset_name=dataset_name,
                    row_number=int(row_index) + 1,
                    column_name="Entire Record",
                    issue_type="Duplicate Record",
                    severity="Medium",
                    expected_value="Unique Record",
                    actual_value="Duplicate",
                    suggestion="Remove duplicate record",
                )
            )

        if len(dataframe) == 0:
            return 100.0

        return round(
            (
                (len(dataframe) - duplicate_count)
                / len(dataframe)
            )
            * 100,
            2,
        )

    # -------------------------------------------------------------
    # Overall Score
    # -------------------------------------------------------------

    def _calculate_overall_score(
        self,
        metric: DataQualityMetric,
    ) -> float:
        """
        Calculate the weighted overall quality score.
        """

        score = (
            metric.completeness_score * 0.20
            + metric.validity_score * 0.20
            + metric.consistency_score * 0.20
            + metric.accuracy_score * 0.15
            + metric.uniqueness_score * 0.15
            + metric.timeliness_score * 0.10
        )

        return round(score, 2)

    # -------------------------------------------------------------
    # Status
    # -------------------------------------------------------------

    def _determine_status(
        self,
        score: float,
    ) -> str:
        """
        Determine quality classification.
        """

        if score >= 95:
            return "Excellent"

        if score >= 85:
            return "Good"

        if score >= 70:
            return "Fair"

        if score >= 50:
            return "Poor"

        return "Critical"
