from src.ic03.services.relationship_query_service import (
    RelationshipQueryService,
)


class RelationshipQueryReport:
    """
    Prints relationship query information generated by the
    RelationshipQueryService.
    """

    def __init__(self, query_service: RelationshipQueryService):
        self.query_service = query_service

    def print_report(self):
        print("=" * 70)
        print("              RELATIONSHIP QUERY REPORT")
        print("=" * 70)

        self.print_repository_statistics()
        self.print_relationship_types()
        self.print_method_calls()
        self.print_imports()
        self.print_inheritance()
        self.print_summary()

    # ---------------------------------------------------------
    # Repository Statistics
    # ---------------------------------------------------------

    def print_repository_statistics(self):
        print("\nRepository Statistics")
        print("-" * 40)

        print(
            f"Total Relationships : "
            f"{self.query_service.count_relationships()}"
        )

    # ---------------------------------------------------------
    # Relationship Types
    # ---------------------------------------------------------

    def print_relationship_types(self):
        print("\nRelationship Types")
        print("-" * 40)

        summary = self.query_service.relationship_summary()

        if not summary:
            print("No relationships found.")
            return

        for relationship_type in sorted(summary):
            print(
                f"{relationship_type:<25}"
                f"{summary[relationship_type]}"
            )

    # ---------------------------------------------------------
    # Method Calls
    # ---------------------------------------------------------

    def print_method_calls(self):
        print("\nMethod Calls")
        print("-" * 40)

        calls = self.query_service.get_method_calls()

        if not calls:
            print("No method calls discovered.")
            return

        for call in calls:
            print(f"{call.source}  --->  {call.target}")

    # ---------------------------------------------------------
    # Imports
    # ---------------------------------------------------------

    def print_imports(self):
        print("\nImports")
        print("-" * 40)

        imports = self.query_service.get_imports()

        if not imports:
            print("No imports discovered.")
            return

        for relation in imports:
            print(f"{relation.source}  --->  {relation.target}")

    # ---------------------------------------------------------
    # Inheritance
    # ---------------------------------------------------------

    def print_inheritance(self):
        print("\nInheritance")
        print("-" * 40)

        inheritance = self.query_service.get_inheritance_relationships()

        if not inheritance:
            print("No inheritance discovered.")
            return

        for relation in inheritance:
            print(f"{relation.source}  --->  {relation.target}")

    # ---------------------------------------------------------
    # Summary
    # ---------------------------------------------------------

    def print_summary(self):
        print("\nSummary")
        print("-" * 40)

        summary = self.query_service.relationship_summary()

        print(
            f"Total Relationship Types : "
            f"{len(summary)}"
        )

        print(
            f"Total Relationships      : "
            f"{self.query_service.count_relationships()}"
        )

        print("=" * 70)
